### ISSUE TITLE
Bank Script

### ISSUE THREAD

**Issue by Marketingguru** [fmorris2/FC_Questing#1]
Hello, this isn't an issue but I didn't feel like you would want me to email you directly. Do you think you could make a script that would trade items from your bank to your mule? Have a simple GUI that lists out all the items in the bank and you can select which ones you want to trade and then it will trade taking them out of the bank and trading them?

**Comment by fmorris2** [comment]
Yes, I could make this. Unfortunately I'm not a premium scripter at the moment though, so we'll have to wait on this.

Contact me again through the TRiBot messenger when I achieve the premium scripter rank (shouldn't be too much longer).
